# Generated by Django 3.2.8 on 2022-02-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='registeruser',
        ),
    ]
